[package]
edition = "2021"
name = "backend-rs"
version = "0.0.0"
rust-version = "1.74"

[features]
default = []
napi = ["dep:napi", "dep:napi-derive"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
macro_rs = { workspace = true }

napi = { workspace = true, optional = true, default-features = false, features = ["napi9", "tokio_rt", "chrono_date", "serde-json"] }
napi-derive = { workspace = true, optional = true }

async-trait = { workspace = true }
basen = { workspace = true }
cfg-if = { workspace = true }
chrono = { workspace = true }
cuid2 = { workspace = true }
jsonschema = { workspace = true }
once_cell = { workspace = true }
parse-display = { workspace = true }
rand = { workspace = true }
regex = { workspace = true }
schemars = { workspace = true, features = ["chrono"] }
sea-orm = { workspace = true, features = ["sqlx-postgres", "runtime-tokio-rustls"] }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }

[dev-dependencies]
pretty_assertions = { workspace = true }

[build-dependencies]
napi-build = { workspace = true }
