[package]
name = "macro-rs"
version = "0.0.0"
edition = "2021"
rust-version = "1.74"

[lib]
proc-macro = true

[dependencies]
convert_case = { workspace = true }
proc-macro2 = { workspace = true }
quote = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
syn = { workspace = true, features = ["full", "extra-traits"] }

[dev-dependencies]
thiserror = { workspace = true }
napi = { workspace = true }
napi-derive = { workspace = true, features = ["noop"] }
